
JND:
  hostname: jnd-devdb-scan.onsemi.com #jnd-proddb-scan
  port: 1537 #1540
  serviceName: JNDMFGQ.onsemi.com #JNDMFGP.onsemi.com
  username: DATAPORT_USER
  password: Aizu1234
  dataType:
    - Probe:
        testerType:
          - TESEC:
              senderId: 62 #81
          - TERAPROBE:
             senderId: 13 #83
    - FinalTest:
        testerType:
          - A1:
              senderId: 01
CZ4:
  hostname: cz4hostename
  port: 1234
  serviceName: czrservicename
  username: CZ4_USERNAME_ENV
  password: CZ4_PASSWORD_ENV
  dataType:
    - Probe:
        testerType:
          - TESEC:
              senderId: 82
    - FinalTest:
        testerType:
          - A1:
              senderId: 02